### ISSUE TITLE
为什么项目运行起来直接提示无效的api，并且选择打开文件没反应呢

### ISSUE THREAD

**Issue by skx001** [DLTech21/ofd-vue-demo#1]
![image](https://user-images.githubusercontent.com/96520555/217458644-7c66adbe-8c38-435e-8944-1fb438d53abf.png)

**Comment by DLTech21** [comment]
加vx

**Comment by leo-joy** [comment]
我的运行之后也是显示这样的？ 怎么解决呢？请大神赐教！
