### ISSUE TITLE
引入了最新版的ofd-view@1.0.57报错

### ISSUE THREAD

**Issue by aLLeENSmith** [DLTech21/ofd-vue-demo#2]
Cannot read properties of undefined (reading 'initOFDViewer')

![image](https://github.com/DLTech21/ofd-vue-demo/assets/31880062/1cccab41-a30c-483d-b723-5f9c8ea34550)

**Comment by aLLeENSmith** [comment]
已解决

**Comment by DuyinLoo88** [comment]
咋解决了？
